//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace StageBitz.AdminWeb.ItemTypes {
    
    
    public partial class ItemTypeFieldPreferences {
        
        /// <summary>
        /// gvItemTypeFieldPreference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StageBitz.AdminWeb.Controls.Common.SBRadGrid gvItemTypeFieldPreference;
        
        /// <summary>
        /// btnSaveFieldPreferences control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSaveFieldPreferences;
        
        /// <summary>
        /// popupSavedChanges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StageBitz.AdminWeb.Controls.Common.PopupBox popupSavedChanges;
        
        /// <summary>
        /// popupSavingChanges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StageBitz.AdminWeb.Controls.Common.PopupBox popupSavingChanges;
    }
}
