// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Geveo.StageBitz.Test.Common
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// InvokePersonalDashboard
        /// </summary>
        public void InvokePersonalDashboard()
        {
            #region Variable Declarations
            HtmlHyperlink uIHomeHyperlink = this.UIProfessionalPropsManWindow.UIProfessionalPropsManDocument1.UIHomeHyperlink;
            #endregion

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink, new Point(17, 10));
        }
        
        /// <summary>
        /// LoginUserPortal - Use 'LoginUserPortalParams' to pass parameters into this method.
        /// </summary>
        public void LoginUserPortal()
        {
            #region Variable Declarations
            HtmlEdit uIEmailAddressEdit = this.UIWelcometoStageBitzWiWindow.UIWelcometoStageBitzDocument1.UIEmailAddressEdit;
            HtmlEdit uIPasswordEdit = this.UIWelcometoStageBitzWiWindow.UIWelcometoStageBitzDocument1.UIPasswordEdit;
            HtmlInputButton uISignInButton = this.UIWelcometoStageBitzWiWindow.UIWelcometoStageBitzDocument1.UISignInButton;
            #endregion

            // Type 'piu5001@mailinator.com' in 'Email Address' text box
            uIEmailAddressEdit.Text = this.LoginUserPortalParams.UIEmailAddressEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LoginUserPortalParams.UIPasswordEditPassword;

            // Click 'Sign In' button
            Mouse.Click(uISignInButton, new Point(14, 9));
        }
        
        /// <summary>
        /// LogoutFromUserPortal
        /// </summary>
        public void LogoutFromUserPortal()
        {
            #region Variable Declarations
            HtmlHyperlink uISignOutHyperlink = this.UIStageBitzInternetExpWindow.UIStageBitzDocument.UIWelcomepiu5001TestSiPane.UISignOutHyperlink;
            #endregion

            // Click 'Sign Out' link
            Mouse.Click(uISignOutHyperlink, new Point(32, 14));
        }
        
        #region Properties
        public virtual LoginUserPortalParams LoginUserPortalParams
        {
            get
            {
                if ((this.mLoginUserPortalParams == null))
                {
                    this.mLoginUserPortalParams = new LoginUserPortalParams();
                }
                return this.mLoginUserPortalParams;
            }
        }
        
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIStartmenuWindow UIStartmenuWindow
        {
            get
            {
                if ((this.mUIStartmenuWindow == null))
                {
                    this.mUIStartmenuWindow = new UIStartmenuWindow();
                }
                return this.mUIStartmenuWindow;
            }
        }
        
        public UIGoogleWindowsInterneWindow UIGoogleWindowsInterneWindow
        {
            get
            {
                if ((this.mUIGoogleWindowsInterneWindow == null))
                {
                    this.mUIGoogleWindowsInterneWindow = new UIGoogleWindowsInterneWindow();
                }
                return this.mUIGoogleWindowsInterneWindow;
            }
        }
        
        public UIWelcometoStageBitzWiWindow UIWelcometoStageBitzWiWindow
        {
            get
            {
                if ((this.mUIWelcometoStageBitzWiWindow == null))
                {
                    this.mUIWelcometoStageBitzWiWindow = new UIWelcometoStageBitzWiWindow();
                }
                return this.mUIWelcometoStageBitzWiWindow;
            }
        }
        
        public UIProfessionalPropsManWindow UIProfessionalPropsManWindow
        {
            get
            {
                if ((this.mUIProfessionalPropsManWindow == null))
                {
                    this.mUIProfessionalPropsManWindow = new UIProfessionalPropsManWindow();
                }
                return this.mUIProfessionalPropsManWindow;
            }
        }
        
        public UIStageBitzInternetExpWindow UIStageBitzInternetExpWindow
        {
            get
            {
                if ((this.mUIStageBitzInternetExpWindow == null))
                {
                    this.mUIStageBitzInternetExpWindow = new UIStageBitzInternetExpWindow();
                }
                return this.mUIStageBitzInternetExpWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginUserPortalParams mLoginUserPortalParams;
        
        private UIStartWindow mUIStartWindow;
        
        private UIStartmenuWindow mUIStartmenuWindow;
        
        private UIGoogleWindowsInterneWindow mUIGoogleWindowsInterneWindow;
        
        private UIWelcometoStageBitzWiWindow mUIWelcometoStageBitzWiWindow;
        
        private UIProfessionalPropsManWindow mUIProfessionalPropsManWindow;
        
        private UIStageBitzInternetExpWindow mUIStageBitzInternetExpWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginUserPortal'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class LoginUserPortalParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'piu5001@mailinator.com' in 'Email Address' text box
        /// </summary>
        public string UIEmailAddressEditText = "piu5001@mailinator.com";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "nAO6FE+d177p7uXi8Xo+YDTB4TP2UBvd";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIStartWindow : WinWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public WinButton UIStartButton
        {
            get
            {
                if ((this.mUIStartButton == null))
                {
                    this.mUIStartButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStartButton.SearchProperties[WinButton.PropertyNames.Name] = "Start";
                    this.mUIStartButton.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIStartButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStartButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIStartmenuWindow : WinWindow
    {
        
        public UIStartmenuWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start menu";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIFavoritesWindow UIFavoritesWindow
        {
            get
            {
                if ((this.mUIFavoritesWindow == null))
                {
                    this.mUIFavoritesWindow = new UIFavoritesWindow(this);
                }
                return this.mUIFavoritesWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIFavoritesWindow mUIFavoritesWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "4";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIStartmenuClient UIStartmenuClient
        {
            get
            {
                if ((this.mUIStartmenuClient == null))
                {
                    this.mUIStartmenuClient = new UIStartmenuClient(this);
                }
                return this.mUIStartmenuClient;
            }
        }
        #endregion
        
        #region Fields
        private UIStartmenuClient mUIStartmenuClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIStartmenuClient : WinClient
    {
        
        public UIStartmenuClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAllProgramsMenuItem
        {
            get
            {
                if ((this.mUIAllProgramsMenuItem == null))
                {
                    this.mUIAllProgramsMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAllProgramsMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "All Programs";
                    this.mUIAllProgramsMenuItem.WindowTitles.Add("Start menu");
                    #endregion
                }
                return this.mUIAllProgramsMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAllProgramsMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFavoritesWindow : WinWindow
    {
        
        public UIFavoritesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "100";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIFavoritesTree UIFavoritesTree
        {
            get
            {
                if ((this.mUIFavoritesTree == null))
                {
                    this.mUIFavoritesTree = new UIFavoritesTree(this);
                }
                return this.mUIFavoritesTree;
            }
        }
        #endregion
        
        #region Fields
        private UIFavoritesTree mUIFavoritesTree;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFavoritesTree : WinTree
    {
        
        public UIFavoritesTree(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTree.PropertyNames.Name] = "All Programs";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIInternetExplorerMenuItem
        {
            get
            {
                if ((this.mUIInternetExplorerMenuItem == null))
                {
                    this.mUIInternetExplorerMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIInternetExplorerMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Internet Explorer";
                    this.mUIInternetExplorerMenuItem.WindowTitles.Add("Start menu");
                    #endregion
                }
                return this.mUIInternetExplorerMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIInternetExplorerMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIGoogleWindowsInterneWindow : BrowserWindow
    {
        
        public UIGoogleWindowsInterneWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Google";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGoogleDocument UIGoogleDocument
        {
            get
            {
                if ((this.mUIGoogleDocument == null))
                {
                    this.mUIGoogleDocument = new UIGoogleDocument(this);
                }
                return this.mUIGoogleDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleDocument mUIGoogleDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIGoogleDocument : HtmlDocument
    {
        
        public UIGoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "gsr";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.google.lk/";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIImagesHyperlink
        {
            get
            {
                if ((this.mUIImagesHyperlink == null))
                {
                    this.mUIImagesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIImagesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "gb_2";
                    this.mUIImagesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIImagesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIImagesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Images";
                    this.mUIImagesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/imghp";
                    this.mUIImagesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIImagesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.google.lk/imghp?hl=en&tab=wi";
                    this.mUIImagesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "gbzt";
                    this.mUIImagesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"gb_2\" class=\"gbzt\" onclick=\"gbar.qs(";
                    this.mUIImagesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIImagesHyperlink.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIImagesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIImagesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWelcometoStageBitzWiWindow : BrowserWindow
    {
        
        public UIWelcometoStageBitzWiWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Welcome to StageBitz!";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Welcome to StageBitz!");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIWelcometoStageBitzDocument UIWelcometoStageBitzDocument
        {
            get
            {
                if ((this.mUIWelcometoStageBitzDocument == null))
                {
                    this.mUIWelcometoStageBitzDocument = new UIWelcometoStageBitzDocument(this);
                }
                return this.mUIWelcometoStageBitzDocument;
            }
        }
        
        public UIWelcometoStageBitzDocument1 UIWelcometoStageBitzDocument1
        {
            get
            {
                if ((this.mUIWelcometoStageBitzDocument1 == null))
                {
                    this.mUIWelcometoStageBitzDocument1 = new UIWelcometoStageBitzDocument1(this);
                }
                return this.mUIWelcometoStageBitzDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIWelcometoStageBitzDocument mUIWelcometoStageBitzDocument;
        
        private UIWelcometoStageBitzDocument1 mUIWelcometoStageBitzDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWelcometoStageBitzDocument : HtmlDocument
    {
        
        public UIWelcometoStageBitzDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Welcome to StageBitz!";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Account/Login.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/StageBitz.DevUserWeb/Account/Login.aspx";
            this.WindowTitles.Add("Welcome to StageBitz!");
            #endregion
        }
        
        #region Properties
        public HtmlEdit tbxUserName
        {
            get
            {
                if ((this.mtbxUserName == null))
                {
                    this.mtbxUserName = new HtmlEdit(this);
                    #region Search Criteria
                    this.mtbxUserName.SearchProperties[HtmlEdit.PropertyNames.Id] = "MainContent_txtUsername";
                    this.mtbxUserName.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$txtUsername";
                    this.mtbxUserName.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email Address";
                    this.mtbxUserName.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mtbxUserName.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mtbxUserName.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mtbxUserName.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=\"MainContent_txtUsername\" name=\"ctl00";
                    this.mtbxUserName.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mtbxUserName.WindowTitles.Add("Welcome to StageBitz!");
                    #endregion
                }
                return this.mtbxUserName;
            }
        }
        
        public HtmlEdit tbxPassword
        {
            get
            {
                if ((this.mtbxPassword == null))
                {
                    this.mtbxPassword = new HtmlEdit(this);
                    #region Search Criteria
                    this.mtbxPassword.SearchProperties[HtmlEdit.PropertyNames.Id] = "MainContent_txtPassword";
                    this.mtbxPassword.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$txtPassword";
                    this.mtbxPassword.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mtbxPassword.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mtbxPassword.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mtbxPassword.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mtbxPassword.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=\"MainContent_txtPassword\" name=\"ctl00";
                    this.mtbxPassword.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mtbxPassword.WindowTitles.Add("Welcome to StageBitz!");
                    #endregion
                }
                return this.mtbxPassword;
            }
        }
        
        public HtmlInputButton btnSignIn
        {
            get
            {
                if ((this.mbtnSignIn == null))
                {
                    this.mbtnSignIn = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mbtnSignIn.SearchProperties[HtmlButton.PropertyNames.Id] = "MainContent_btnSignIn";
                    this.mbtnSignIn.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$MainContent$btnSignIn";
                    this.mbtnSignIn.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Sign In";
                    this.mbtnSignIn.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mbtnSignIn.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mbtnSignIn.FilterProperties[HtmlButton.PropertyNames.Class] = "buttonStyle";
                    this.mbtnSignIn.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"MainContent_btnSignIn\" class=\"button";
                    this.mbtnSignIn.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "10";
                    this.mbtnSignIn.WindowTitles.Add("Welcome to StageBitz!");
                    #endregion
                }
                return this.mbtnSignIn;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mtbxUserName;
        
        private HtmlEdit mtbxPassword;
        
        private HtmlInputButton mbtnSignIn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWelcometoStageBitzDocument1 : HtmlDocument
    {
        
        public UIWelcometoStageBitzDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Welcome to StageBitz!";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Account/Login.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/StageBitz.DevUserWeb/Account/Login.aspx?ReturnUrl=%2fStageBitz.D" +
                "evUserWeb%2f";
            this.WindowTitles.Add("Welcome to StageBitz!");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEmailAddressEdit
        {
            get
            {
                if ((this.mUIEmailAddressEdit == null))
                {
                    this.mUIEmailAddressEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "MainContent_txtUsername";
                    this.mUIEmailAddressEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$txtUsername";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email Address";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$txtUsername\" id=";
                    this.mUIEmailAddressEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUIEmailAddressEdit.WindowTitles.Add("Welcome to StageBitz!");
                    #endregion
                }
                return this.mUIEmailAddressEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "MainContent_txtPassword";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$txtPassword";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$txtPassword\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUIPasswordEdit.WindowTitles.Add("Welcome to StageBitz!");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlInputButton UISignInButton
        {
            get
            {
                if ((this.mUISignInButton == null))
                {
                    this.mUISignInButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Id] = "MainContent_btnSignIn";
                    this.mUISignInButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$MainContent$btnSignIn";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Sign In";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.Class] = "buttonStyle";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$btnSignIn\" class";
                    this.mUISignInButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "10";
                    this.mUISignInButton.WindowTitles.Add("Welcome to StageBitz!");
                    #endregion
                }
                return this.mUISignInButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEmailAddressEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlInputButton mUISignInButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIProfessionalPropsManWindow : BrowserWindow
    {
        
        public UIProfessionalPropsManWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Professional Props Management | StageBitz";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Professional Props Management | StageBitz");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIProfessionalPropsManDocument UIProfessionalPropsManDocument
        {
            get
            {
                if ((this.mUIProfessionalPropsManDocument == null))
                {
                    this.mUIProfessionalPropsManDocument = new UIProfessionalPropsManDocument(this);
                }
                return this.mUIProfessionalPropsManDocument;
            }
        }
        
        public UIProfessionalPropsManDocument1 UIProfessionalPropsManDocument1
        {
            get
            {
                if ((this.mUIProfessionalPropsManDocument1 == null))
                {
                    this.mUIProfessionalPropsManDocument1 = new UIProfessionalPropsManDocument1(this);
                }
                return this.mUIProfessionalPropsManDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIProfessionalPropsManDocument mUIProfessionalPropsManDocument;
        
        private UIProfessionalPropsManDocument1 mUIProfessionalPropsManDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIProfessionalPropsManDocument : HtmlDocument
    {
        
        public UIProfessionalPropsManDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Professional Props Management | StageBitz";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Default.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/StageBitz.DevUserWeb/Default.aspx";
            this.WindowTitles.Add("Professional Props Management | StageBitz");
            #endregion
        }
        
        #region Properties
        public UIWelcomeAuto14TestSigPane UIWelcomeAuto14TestSigPane
        {
            get
            {
                if ((this.mUIWelcomeAuto14TestSigPane == null))
                {
                    this.mUIWelcomeAuto14TestSigPane = new UIWelcomeAuto14TestSigPane(this);
                }
                return this.mUIWelcomeAuto14TestSigPane;
            }
        }
        #endregion
        
        #region Fields
        private UIWelcomeAuto14TestSigPane mUIWelcomeAuto14TestSigPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWelcomeAuto14TestSigPane : HtmlDiv
    {
        
        public UIWelcomeAuto14TestSigPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "NavigationContent_divUserInfo";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "\r\nWelcome Auto14 Test  \r\n\r\n| Sign Out";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "right userInfo";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"NavigationContent_divUserInfo\" class";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "15";
            this.WindowTitles.Add("Professional Props Management | StageBitz");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink lnkSignOut
        {
            get
            {
                if ((this.mlnkSignOut == null))
                {
                    this.mlnkSignOut = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mlnkSignOut.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mlnkSignOut.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mlnkSignOut.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mlnkSignOut.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sign Out";
                    this.mlnkSignOut.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Account/Logout.aspx";
                    this.mlnkSignOut.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mlnkSignOut.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/StageBitz.DevUserWeb/Account/Logout.aspx";
                    this.mlnkSignOut.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mlnkSignOut.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"Account/Logout.aspx\"";
                    this.mlnkSignOut.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mlnkSignOut.WindowTitles.Add("Professional Props Management | StageBitz");
                    #endregion
                }
                return this.mlnkSignOut;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mlnkSignOut;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIProfessionalPropsManDocument1 : HtmlDocument
    {
        
        public UIProfessionalPropsManDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Professional Props Management | StageBitz";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Company/CompanyAdministrator.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/StageBitz.DevUserWeb/Company/CompanyAdministrator.aspx?companyid" +
                "=176";
            this.WindowTitles.Add("Professional Props Management | StageBitz");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "NavigationContent_lnkHomePage";
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Default.aspx";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/StageBitz.DevUserWeb/Default.aspx";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"NavigationContent_lnkHomePage\" href=";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIHomeHyperlink.WindowTitles.Add("Professional Props Management | StageBitz");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIStageBitzInternetExpWindow : BrowserWindow
    {
        
        public UIStageBitzInternetExpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "StageBitz";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("StageBitz");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIStageBitzDocument UIStageBitzDocument
        {
            get
            {
                if ((this.mUIStageBitzDocument == null))
                {
                    this.mUIStageBitzDocument = new UIStageBitzDocument(this);
                }
                return this.mUIStageBitzDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIStageBitzDocument mUIStageBitzDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIStageBitzDocument : HtmlDocument
    {
        
        public UIStageBitzDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "StageBitz";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Default.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost/StageBitz.DevUserWeb/Default.aspx";
            this.WindowTitles.Add("StageBitz");
            #endregion
        }
        
        #region Properties
        public UIWelcomepiu5001TestSiPane UIWelcomepiu5001TestSiPane
        {
            get
            {
                if ((this.mUIWelcomepiu5001TestSiPane == null))
                {
                    this.mUIWelcomepiu5001TestSiPane = new UIWelcomepiu5001TestSiPane(this);
                }
                return this.mUIWelcomepiu5001TestSiPane;
            }
        }
        #endregion
        
        #region Fields
        private UIWelcomepiu5001TestSiPane mUIWelcomepiu5001TestSiPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIWelcomepiu5001TestSiPane : HtmlDiv
    {
        
        public UIWelcomepiu5001TestSiPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "NavigationContent_divUserInfo";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Welcome piu5001 Test  \r\n\r\n| Sign Out ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "right userInfo";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"right userInfo\" id=\"NavigationContent_divUserInfo\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
            this.WindowTitles.Add("StageBitz");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISignOutHyperlink
        {
            get
            {
                if ((this.mUISignOutHyperlink == null))
                {
                    this.mUISignOutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISignOutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISignOutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISignOutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISignOutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sign Out";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/StageBitz.DevUserWeb/Account/Logout.aspx";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost/StageBitz.DevUserWeb/Account/Logout.aspx";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"Account/Logout.aspx\"";
                    this.mUISignOutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUISignOutHyperlink.WindowTitles.Add("StageBitz");
                    #endregion
                }
                return this.mUISignOutHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISignOutHyperlink;
        #endregion
    }
}
